ALTER TABLE users DROP CONSTRAINT IF EXISTS users_fk0;

ALTER TABLE matches DROP CONSTRAINT IF EXISTS matches_fk0;

ALTER TABLE matches DROP CONSTRAINT IF EXISTS matches_fk1;

ALTER TABLE matches DROP CONSTRAINT IF EXISTS matches_fk2;

ALTER TABLE teams DROP CONSTRAINT IF EXISTS teams_fk0;

ALTER TABLE bets DROP CONSTRAINT IF EXISTS bets_fk0;

ALTER TABLE bets DROP CONSTRAINT IF EXISTS bets_fk1;

ALTER TABLE bets DROP CONSTRAINT IF EXISTS bets_fk2;

DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS pictures CASCADE ;

DROP TABLE IF EXISTS sport_games CASCADE;

DROP TABLE IF EXISTS matches CASCADE;

DROP TABLE IF EXISTS teams CASCADE;

DROP TABLE IF EXISTS bets CASCADE;
